version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8080:8080"
    secrets:
      - gcloud-service-account
    networks:
      - genotracker-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    secrets:
      - gcloud-service-account
    networks:
      - genotracker-network

secrets:
  gcloud-service-account:
    file: ./secrets/gp2-release-terra-e65c1b67820b.json

networks:
  genotracker-network:
    driver: bridge