FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install poetry

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-dev

COPY . /app

# use this for local testing
# ENV GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcloud-service-account

EXPOSE 8080

CMD ["uvicorn", "genotracker.main:app", "--host", "0.0.0.0", "--port", "8080"]