from typing import Optional
from pydantic import BaseModel, Field
from datetime import date

class CohortDataSchema(BaseModel):
    study_code: Optional[str] = ''
    monogenic_complex_mixed: Optional[str] = ''
    institution: Optional[str] = ''
    city: Optional[str] = ''
    location: Optional[str] = ''
    territory: Optional[str] = ''
    n_dna_samples_attempted: Optional[int] = 0
    total_qc_pass: Optional[int] = 0
    callrate_fails: Optional[int] = 0
    sex_fails: Optional[int] = 0
    het_fails: Optional[int] = 0
    duplicates: Optional[int] = 0
    genotyping_complete: Optional[bool] = False
    imputation_panel: Optional[str] = ''
    imputation_complete: Optional[bool] = False
    genotypes_shareable: Optional[bool] = False
    shared_to_amppd: Optional[bool] = False
    gdpr: Optional[bool] = False
    site: Optional[str] = ''
    afr_case: Optional[int] = 0
    afr_control: Optional[int] = 0
    afr_other: Optional[int] = 0
    aac_case: Optional[int] = 0
    aac_control: Optional[int] = 0
    aac_other: Optional[int] = 0
    aj_case: Optional[int] = 0
    aj_control: Optional[int] = 0
    aj_other: Optional[int] = 0
    eas_case: Optional[int] = 0
    eas_control: Optional[int] = 0
    eas_other: Optional[int] = 0
    eur_case: Optional[int] = 0
    eur_control: Optional[int] = 0
    eur_other: Optional[int] = 0
    fin_case: Optional[int] = 0
    fin_control: Optional[int] = 0
    fin_other: Optional[int] = 0
    amr_case: Optional[int] = 0
    amr_control: Optional[int] = 0
    amr_other: Optional[int] = 0
    sas_case: Optional[int] = 0
    sas_control: Optional[int] = 0
    sas_other: Optional[int] = 0
    cas_case: Optional[int] = 0
    cas_control: Optional[int] = 0
    cas_other: Optional[int] = 0
    mde_case: Optional[int] = 0
    mde_control: Optional[int] = 0
    mde_other: Optional[int] = 0
    cah_case: Optional[int] = 0
    cah_control: Optional[int] = 0
    cah_other: Optional[int] = 0
    total: Optional[int] = 0
    new: Optional[bool] = False
    date_last_update: Optional[date] = Field(default_factory=date.today)
    compliance: Optional[bool] = False